BAPI_ACC_DOCUMENT_POST:
  DOCUMENTHEADER:
    PARAMCLASS: I
    TABNAME: BAPIACHE09
    PARAMTEXT: Header
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: DOCUMENTHEADER
    required: true
    paramType: struct
  CONTRACTHEADER:
    PARAMCLASS: I
    TABNAME: BAPIACCAHD
    PARAMTEXT: Additional Contract Accounts Recievable and Payable Header Line
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: CONTRACTHEADER
    required: false
    default: ''
    paramType: struct
  CUSTOMERCPD:
    PARAMCLASS: I
    TABNAME: BAPIACPA09
    PARAMTEXT: One-time customer
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: CUSTOMERCPD
    required: false
    default: ''
    paramType: struct
  CURRENCYAMOUNT:
    PARAMCLASS: T
    TABNAME: BAPIACCR09
    PARAMTEXT: Currency Items
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: CURRENCYAMOUNT
    required: true
    paramType: table
  RETURN:
    PARAMCLASS: T
    TABNAME: BAPIRET2
    PARAMTEXT: Return parameter
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: RETURN
    required: true
    paramType: table
  ACCOUNTGL:
    PARAMCLASS: T
    TABNAME: BAPIACGL09
    PARAMTEXT: G/L account item
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: ACCOUNTGL
    required: false
    default: ''
    paramType: table
  ACCOUNTPAYABLE:
    PARAMCLASS: T
    TABNAME: BAPIACAP09
    PARAMTEXT: Vendor Item
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: ACCOUNTPAYABLE
    required: false
    default: ''
    paramType: table
  ACCOUNTRECEIVABLE:
    PARAMCLASS: T
    TABNAME: BAPIACAR09
    PARAMTEXT: Customer Item
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: ACCOUNTRECEIVABLE
    required: false
    default: ''
    paramType: table
  ACCOUNTTAX:
    PARAMCLASS: T
    TABNAME: BAPIACTX09
    PARAMTEXT: Tax item
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: ACCOUNTTAX
    required: false
    default: ''
    paramType: table
  ACCOUNTWT:
    PARAMCLASS: T
    TABNAME: BAPIACWT09
    PARAMTEXT: Withholding tax information for FI Interface
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: ACCOUNTWT
    required: false
    default: ''
    paramType: table
  CONTRACTITEM:
    PARAMCLASS: T
    TABNAME: BAPIACCAIT
    PARAMTEXT: Additional Contract Accounts Recieviable and Payable Document Line Item
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: CONTRACTITEM
    required: false
    default: ''
    paramType: table
  CRITERIA:
    PARAMCLASS: T
    TABNAME: BAPIACKEC9
    PARAMTEXT: CO-PA Account Assignment Characteristics
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: CRITERIA
    required: false
    default: ''
    paramType: table
  EXTENSION1:
    PARAMCLASS: T
    TABNAME: BAPIACEXTC
    PARAMTEXT: Container for 'Customer Exit' Parameter
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: EXTENSION1
    required: false
    default: ''
    paramType: table
  EXTENSION2:
    PARAMCLASS: T
    TABNAME: BAPIPAREX
    PARAMTEXT: Reference Structure for BAPI Parameters EXTENSIONIN/EXTENSIONOUT
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: EXTENSION2
    required: false
    default: ''
    paramType: table
  PAYMENTCARD:
    PARAMCLASS: T
    TABNAME: BAPIACPC09
    PARAMTEXT: Payment Card Information
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: PAYMENTCARD
    required: false
    default: ''
    paramType: table
  REALESTATE:
    PARAMCLASS: T
    TABNAME: BAPIACRE09
    PARAMTEXT: Real Estate Account Assignment Data
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: REALESTATE
    required: false
    default: ''
    paramType: table
  VALUEFIELD:
    PARAMCLASS: T
    TABNAME: BAPIACKEV9
    PARAMTEXT: CO-PA Account Assignment Value Fields
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: VALUEFIELD
    required: false
    default: ''
    paramType: table
  OBJ_KEY:
    PARAMCLASS: E
    TABNAME: BAPIACHE09
    FIELDNAME: OBJ_KEY
    PARAMTEXT: Reference key
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: OBJ_KEY
    required: true
    paramType: var
  OBJ_SYS:
    PARAMCLASS: E
    TABNAME: BAPIACHE09
    FIELDNAME: OBJ_SYS
    PARAMTEXT: Logical system of source document
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: OBJ_SYS
    required: true
    paramType: var
  OBJ_TYPE:
    PARAMCLASS: E
    TABNAME: BAPIACHE09
    FIELDNAME: OBJ_TYPE
    PARAMTEXT: Reference procedure
    functionName: BAPI_ACC_DOCUMENT_POST
    paramName: OBJ_TYPE
    required: true
    paramType: var
