serviceOrder:
  - /COE/RBP_PAM_SERVICE_ORD_CREAT # Create one instance of Service Order object
  - /COE/RBP_PAM_SERV_ORD_CREAT_N # Create Service Order from Notification
  - /COE/RBP_PAM_SERVICE_ORD_GET # Get details of one Service Order object
  - /COE/RBP_PAM_SERVICE_ORD_CC # Calculate costs of one instance of Service Order object
  - /COE/RBP_PAM_SERVICE_ORD_GETL # Get a Service Orders' list
  - /COE/RBP_PAM_SERVICE_ORD_CHANG # Change one instance of Service Order object

